weather.api.key=6fafb477b4fc4e87a7a133518260707
weather.api.city=Buenos Aires

clima.scheduler.obtener=300000
clima.scheduler.evaluar=60000

clima.mail.destinatarios=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

spring.datasource.url=jdbc:h2:mem:climalert
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cecheconea@frba.utn.edu.ar
spring.mail.password=password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true